sonar.projectKey=network-guardian
sonar.projectName=Network Guardian
sonar.projectVersion=1.0.0

sonar.sources=network_guardian
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.python.version=3.13

sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/.pytest_cache/**,*.egg-info/**
sonar.test.inclusions=tests/**/*.py
