"""
Threat analyzer for ng-probe — analyzes discovered networks and hosts for security issues.

Generates threat events based on:
  - WiFi network security (unencrypted networks, weak protocols)
  - Open services on discovered hosts
  - Suspicious port activity
  - Network reconnaissance exposure
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger("ng-probe.threat-analyzer")


@dataclass
class ThreatAlert:
    """A threat alert generated by the probe during network analysis."""
    
    alert_id: str
    threat_type: str  # e.g., "unencrypted_network", "open_service", "suspicious_port"
    severity: str  # critical, high, medium, low
    source_ip: str = ""
    target_ip: str = ""
    target_port: int = 0
    description: str = ""
    affected_items: list[str] = field(default_factory=list)
    remediation: str = ""

    def to_dict(self) -> dict:
        return {
            "alert_id": self.alert_id,
            "threat_type": self.threat_type,
            "severity": self.severity,
            "source_ip": self.source_ip,
            "target_ip": self.target_ip,
            "target_port": self.target_port,
            "description": self.description,
            "affected_items": self.affected_items,
            "remediation": self.remediation,
        }


class ProbeThrottleAnalyzer:
    """Analyzes discovered WiFi networks and hosts for security threats."""

    # Common insecure ports
    INSECURE_PORTS = {
        21: ("FTP", "Unencrypted file transfer"),
        23: ("Telnet", "Unencrypted terminal access"),
        80: ("HTTP", "Unencrypted web server"),
        3306: ("MySQL", "Unencrypted database access"),
        5432: ("PostgreSQL", "Unencrypted database access"),
        6379: ("Redis", "Unencrypted caching service"),
        11211: ("Memcached", "Unencrypted cache store"),
        27017: ("MongoDB", "Unencrypted database"),
        50070: ("Hadoop NameNode", "Unencrypted big data"),
    }

    # Common secure ports (for reference)
    SECURE_PORTS = {
        22: "SSH",
        443: "HTTPS",
        465: "SMTPS",
        587: "SMTP",
        636: "LDAPS",
        3306: "MySQL SSL",
        5432: "PostgreSQL SSL",
        8443: "HTTPS alt",
    }

    # WiFi security ratings
    WIFI_SECURITY_LEVELS = {
        "Open": 0,  # No encryption
        "WEP": 1,   # Deprecated, breakable
        "WPA": 2,   # Legacy, acceptable
        "WPA2": 3,  # Current standard
        "WPA3": 4,  # Latest, best
    }

    def __init__(self):
        self.alerts: list[ThreatAlert] = []
        self._alert_counter = 0

    def _generate_alert_id(self) -> str:
        """Generate unique alert ID."""
        self._alert_counter += 1
        return f"PROBE-{self._alert_counter:06d}"

    def analyze_wifi_networks(self, networks: list[dict[str, Any]]) -> list[ThreatAlert]:
        """Analyze WiFi networks for security issues."""
        self.alerts.clear()

        unencrypted = []
        weak_security = []

        for net in networks:
            ssid = net.get("ssid", "")
            if not ssid or ssid == "(hidden)":
                continue

            security = net.get("security", "Open")

            # Check for unencrypted networks
            if security == "Open":
                unencrypted.append(ssid)
            # Check for deprecated/weak protocols
            elif security in ["WEP", "WPA", "WPA-PSK"]:
                weak_security.append(f"{ssid} ({security})")

        # Generate alerts
        if unencrypted:
            alert = ThreatAlert(
                alert_id=self._generate_alert_id(),
                threat_type="unencrypted_network",
                severity="high",
                description=f"Detected {len(unencrypted)} open WiFi network(s) without encryption",
                affected_items=unencrypted,
                remediation="Enable WPA2/WPA3 encryption on all WiFi networks",
            )
            self.alerts.append(alert)
            logger.warning("THREAT: Unencrypted WiFi networks: %s", unencrypted)

        if weak_security:
            alert = ThreatAlert(
                alert_id=self._generate_alert_id(),
                threat_type="weak_wifi_security",
                severity="medium",
                description=f"Detected {len(weak_security)} WiFi network(s) with deprecated security",
                affected_items=weak_security,
                remediation="Upgrade all networks to WPA2 or WPA3",
            )
            self.alerts.append(alert)
            logger.warning("THREAT: Weak WiFi security: %s", weak_security)

        return self.alerts

    def analyze_discovered_hosts(self, hosts: list[dict[str, Any]],
                                local_subnet: str = "") -> list[ThreatAlert]:
        """Analyze discovered hosts for open services and other issues."""
        if not hosts:
            logger.info("No hosts discovered for analysis")
            return self.alerts

        insecure_services = []

        for host in hosts:
            ip = host.get("ip", "")
            if not ip:
                continue

            # Check for open insecure ports
            open_ports = host.get("open_ports", [])
            if not open_ports:
                continue

            for port in open_ports:
                if port in self.INSECURE_PORTS:
                    service_name, description = self.INSECURE_PORTS[port]
                    insecure_services.append(f"{ip}:{port} ({service_name}) - {description}")

        if insecure_services:
            alert = ThreatAlert(
                alert_id=self._generate_alert_id(),
                threat_type="insecure_service_exposed",
                severity="high",
                description=f"Found {len(insecure_services)} open unencrypted service(s)",
                affected_items=insecure_services,
                remediation="Disable or restrict access to unencrypted services. Use SSH/TLS alternatives.",
            )
            self.alerts.append(alert)
            logger.warning("THREAT: Insecure services exposed: %s", insecure_services)

        return self.alerts

    def analyze_for_reconnaissance(self, networks: list[dict],
                                   host_count: int) -> list[ThreatAlert]:
        """Detect signs we're being scanned/probed."""
        # This is a placeholder for future active reconnaissance detection
        # Could check for:
        #   - Multiple ARP probes to random IPs
        #   - Rapid port scans across hosts
        #   - Multicast DNS queries
        return self.alerts

    def get_threat_summary(self) -> dict[str, Any]:
        """Get summary of threats found."""
        by_severity = {}
        by_type = {}

        for alert in self.alerts:
            sev = alert.severity
            typ = alert.threat_type

            by_severity[sev] = by_severity.get(sev, 0) + 1
            by_type[typ] = by_type.get(typ, 0) + 1

        return {
            "total_threats": len(self.alerts),
            "by_severity": by_severity,
            "by_type": by_type,
            "alerts": [a.to_dict() for a in self.alerts],
        }

    def clear(self) -> None:
        """Clear alert history."""
        self.alerts.clear()
        self._alert_counter = 0
