# Copyright (c) 2026 Wolf-Pak Innovations LLC. All Rights Reserved.
# Proprietary and confidential. Unauthorized use, reproduction,
# or distribution is strictly prohibited. See LICENSE for terms.
"""
AI Component — machine learning and predictive analytics.

Provides pattern recognition, anomaly classification, and recommendation
generation using pluggable ML backends.
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, TYPE_CHECKING

from network_guardian.core.events import Event, EventBus
from network_guardian.models.network import Finding, Host, Metric, Severity

if TYPE_CHECKING:
    from network_guardian.ai.anomaly import AnomalyDetector, EnsembleDetector
    from network_guardian.ai.audit_analyzer import HostRiskProfile, NetworkAuditAnalyzer
    from network_guardian.ai.forecasting import Forecaster, ForecastResult
    from network_guardian.ai.smart_automation import SmartAutomation, TaskRecommendation
    from network_guardian.automator import TaskResult
    from network_guardian.config import Config

logger = logging.getLogger("network_guardian.ai")


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


class PredictionType(Enum):
    ANOMALY = "anomaly"
    CLASSIFICATION = "classification"
    RECOMMENDATION = "recommendation"
    FORECAST = "forecast"


@dataclass
class Prediction:
    """Output of an ML model."""

    prediction_type: PredictionType
    label: str
    confidence: float
    details: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class Recommendation:
    """A recommended action generated by the AI component."""

    title: str
    description: str
    priority: Severity = Severity.INFO
    category: str = "general"
    actions: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Model interface
# ---------------------------------------------------------------------------


class MLModel(ABC):
    """Abstract base class for ML models used by the AI engine."""

    name: str = "base_model"

    @abstractmethod
    async def predict(self, features: dict[str, Any]) -> Prediction:
        """Run inference on a feature set."""

    @abstractmethod
    async def train(self, data: list[dict[str, Any]]) -> dict[str, Any]:
        """Train or fine-tune the model. Returns training metrics."""

    def health_check(self) -> dict[str, Any]:
        return {"model": self.name, "status": "ok"}


# ---------------------------------------------------------------------------
# Built-in models
# ---------------------------------------------------------------------------


class AnomalyClassifier(MLModel):
    """Statistical anomaly classifier (decision-tree-style rules).

    This is a lightweight built-in classifier. For heavy ML workloads,
    register a TensorFlow/PyTorch-backed model via the plugin system.
    """

    name = "anomaly_classifier"

    def __init__(self) -> None:
        self._thresholds: dict[str, float] = {}
        self._trained = False

    async def predict(self, features: dict[str, Any]) -> Prediction:
        value = features.get("value", 0.0)
        metric_name = features.get("metric_name", "unknown")
        threshold = self._thresholds.get(metric_name, 2.0)

        z_score = abs(features.get("z_score", 0.0))
        is_anomaly = z_score > threshold

        confidence = self._compute_confidence(is_anomaly, z_score, threshold)

        return Prediction(
            prediction_type=PredictionType.ANOMALY,
            label="anomaly" if is_anomaly else "normal",
            confidence=confidence,
            details={"metric": metric_name, "value": value, "z_score": z_score},
        )

    @staticmethod
    def _compute_confidence(is_anomaly: bool, z_score: float, threshold: float) -> float:
        if is_anomaly:
            return min(z_score / (threshold * 2), 1.0)
        if threshold:
            return 1.0 - (z_score / threshold)
        return 1.0

    async def train(self, data: list[dict[str, Any]]) -> dict[str, Any]:
        """Learn per-metric thresholds from labelled data."""
        for record in data:
            name = record.get("metric_name", "unknown")
            threshold = record.get("threshold")
            if threshold is not None:
                self._thresholds[name] = float(threshold)
        self._trained = True
        return {"status": "trained", "metrics_configured": len(self._thresholds)}


class PatternRecogniser(MLModel):
    """Rule-based pattern recogniser for network traffic patterns.

    Placeholder for a random-forest / decision-tree model.
    """

    name = "pattern_recogniser"

    def __init__(self) -> None:
        self._patterns: list[dict[str, Any]] = []

    async def predict(self, features: dict[str, Any]) -> Prediction:
        # Placeholder — match against known patterns
        return Prediction(
            prediction_type=PredictionType.CLASSIFICATION,
            label="unknown",
            confidence=0.0,
            details=features,
        )

    async def train(self, data: list[dict[str, Any]]) -> dict[str, Any]:
        self._patterns = data
        return {"status": "trained", "patterns_loaded": len(data)}


# ---------------------------------------------------------------------------
# AI Engine
# ---------------------------------------------------------------------------


class AIEngine:
    """Coordinates ML models and generates recommendations."""

    def __init__(self, config: Config, event_bus: EventBus) -> None:
        self.config = config
        self.event_bus = event_bus
        self._models: dict[str, MLModel] = {}

        # Lazy-initialised advanced subsystems
        self._audit_analyzer: NetworkAuditAnalyzer | None = None
        self._smart_automation: SmartAutomation | None = None
        self._forecasters: dict[str, Forecaster] = {}

        # Register built-in models
        self.register_model(AnomalyClassifier())
        self.register_model(PatternRecogniser())

    def register_model(self, model: MLModel) -> None:
        self._models[model.name] = model
        logger.info("AI model registered: %s", model.name)

    def get_model(self, name: str) -> MLModel:
        return self._models[name]

    async def classify_anomaly(self, features: dict[str, Any]) -> Prediction:
        """Classify whether a metric reading is anomalous."""
        model = self._models["anomaly_classifier"]
        prediction = await model.predict(features)
        if prediction.label == "anomaly":
            await self.event_bus.publish(Event(
                topic="ai.anomaly_detected",
                data={"prediction": prediction},
            ))
        return prediction

    async def recognise_pattern(self, features: dict[str, Any]) -> Prediction:
        """Attempt to classify a network traffic pattern."""
        model = self._models["pattern_recogniser"]
        return await model.predict(features)

    async def generate_recommendations(
        self, findings: list[Finding], metrics: list[Metric]
    ) -> list[Recommendation]:
        """Analyse findings and metrics to produce actionable recommendations."""
        recommendations: list[Recommendation] = []

        # Group findings by severity
        critical = [f for f in findings if f.severity in (Severity.HIGH, Severity.CRITICAL)]
        if critical:
            recommendations.append(Recommendation(
                title="Address critical findings immediately",
                description=f"{len(critical)} high/critical finding(s) detected.",
                priority=Severity.CRITICAL,
                category="security",
                actions=[f"Fix: {f.title} on {f.host}" for f in critical],
            ))

        medium = [f for f in findings if f.severity == Severity.MEDIUM]
        if medium:
            recommendations.append(Recommendation(
                title="Review medium-severity findings",
                description=f"{len(medium)} medium finding(s) should be reviewed.",
                priority=Severity.MEDIUM,
                category="security",
                actions=[f"Review: {f.title}" for f in medium],
            ))

        await self.event_bus.publish(Event(
            topic="ai.recommendations_generated",
            data={"count": len(recommendations)},
        ))
        return recommendations

    @property
    def model_names(self) -> list[str]:
        return list(self._models.keys())

    # -- Advanced subsystems (lazy) -------------------------------------

    @property
    def audit_analyzer(self) -> NetworkAuditAnalyzer:
        """Lazy-initialised network audit analyzer with ensemble detector."""
        if self._audit_analyzer is None:
            from network_guardian.ai.audit_analyzer import NetworkAuditAnalyzer
            self._audit_analyzer = NetworkAuditAnalyzer()
        return self._audit_analyzer

    @property
    def smart_automation(self) -> SmartAutomation:
        """Lazy-initialised smart task automation engine."""
        if self._smart_automation is None:
            from network_guardian.ai.smart_automation import SmartAutomation
            self._smart_automation = SmartAutomation()
        return self._smart_automation

    def get_forecaster(self, method: str = "arima", **kwargs: Any) -> Forecaster:
        """Get or create a forecaster by method name."""
        if method not in self._forecasters:
            if method == "arima":
                from network_guardian.ai.forecasting import ARIMAForecaster
                self._forecasters[method] = ARIMAForecaster(**kwargs)
            elif method == "seasonal":
                from network_guardian.ai.forecasting import SeasonalDecomposer
                self._forecasters[method] = SeasonalDecomposer(**kwargs)
            elif method == "holt_winters":
                from network_guardian.ai.forecasting import HoltWintersForecaster
                self._forecasters[method] = HoltWintersForecaster(**kwargs)
            else:
                raise ValueError(f"Unknown forecaster method: {method}")
        return self._forecasters[method]

    # -- High-level API bridging new modules ----------------------------

    async def forecast(
        self, series: list[float], steps: int = 10, method: str = "arima", **kwargs: Any,
    ) -> ForecastResult:
        """Fit a forecaster on *series* and predict *steps* ahead."""
        forecaster = self.get_forecaster(method, **kwargs)
        forecaster.fit(series)
        result = forecaster.predict(steps)
        await self.event_bus.publish(Event(
            topic="ai.forecast_generated",
            data={"method": method, "steps": steps},
        ))
        return result

    async def analyse_fleet(self, hosts: list[Host]) -> list[HostRiskProfile]:
        """Run audit analysis across a fleet of hosts."""
        profiles = self.audit_analyzer.analyse(hosts)
        await self.event_bus.publish(Event(
            topic="ai.fleet_analysed",
            data={"host_count": len(hosts), "profiles": len(profiles)},
        ))
        return profiles

    async def recommend_tasks(
        self,
        findings: list[Finding],
        available_tasks: list[str],
        history: list[TaskResult] | None = None,
    ) -> list[TaskRecommendation]:
        """Generate prioritised task recommendations from findings."""
        if history:
            self.smart_automation.learn_from_history(history)
        recommendations = self.smart_automation.recommend_tasks(findings, available_tasks)
        await self.event_bus.publish(Event(
            topic="ai.tasks_recommended",
            data={"count": len(recommendations)},
        ))
        return recommendations
